<a href="https://colab.research.google.com/github/MalavikaAjith/Introduction-to-Data-Science/blob/main/01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = [1, 2, 3]
a

[1, 2, 3]

In [ ]:
np.array(a)

array([1, 2, 3])

In [ ]:
b = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [ ]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(2)

array([0.57818787, 0.2664081 ])

In [ ]:
np.random.rand(5,5)

array([[0.96724194, 0.9921777 , 0.10663826, 0.98854691, 0.41653432],
       [0.60032546, 0.57234938, 0.21063235, 0.74275976, 0.97904779],
       [0.55417135, 0.7996001 , 0.22035995, 0.46344146, 0.65757633],
       [0.411062  , 0.9669149 , 0.88318584, 0.90707526, 0.00516818],
       [0.53891131, 0.63197557, 0.33175542, 0.46228729, 0.5687666 ]])

In [ ]:
np.random.randn(2)

array([0.48789279, 0.80217367])

In [ ]:
np.random.randn(5,5)

array([[ 0.26096463,  0.12283968,  0.52243284, -0.64240732,  0.6547696 ],
       [-0.45417576,  0.05335637, -0.99630823, -1.06067155, -0.64950661],
       [ 1.14864524, -1.1200492 ,  0.63685372,  0.56107399, -1.2460059 ],
       [-0.0754311 , -0.02137783, -0.01562501, -0.72907957, -1.2038633 ],
       [-0.09074437, -0.30151518, -0.75765525, -0.32035098,  0.96000653]])

In [ ]:
np.random.randint(0,100)

81

In [ ]:
np.random.randint(0,100,10)

array([53, 85, 94, 71, 54, 32, 53,  5, 34,  7])

In [ ]:
c = np.arange(25)
d = np.random.randint(0,50,10)

In [ ]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
d

array([38, 22,  5,  9, 17, 14,  9, 22, 48, 18])

In [ ]:
c.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
d.max()

48

In [ ]:
d.argmax()

8

In [ ]:
d.min()

5

In [ ]:
d.argmin()

2

In [ ]:
c.shape

(25,)

In [ ]:
c.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
c.reshape(1,25).shape

(1, 25)

In [ ]:
c.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
c.reshape(25,1).shape

(25, 1)

In [ ]:
c.dtype

dtype('int64')