<a href="https://colab.research.google.com/github/MalavikaAjith/Introduction-to-Data-Science/blob/main/02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

In [14]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
a[8]

8

In [16]:
a[1:5]

array([1, 2, 3, 4])

In [17]:
a[0:5]

array([0, 1, 2, 3, 4])

In [18]:
a[0:5] = 100
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [19]:
b = a[0:6]
b

array([100, 100, 100, 100, 100,   5])

In [20]:
b[:] = 99
b

array([99, 99, 99, 99, 99, 99])

In [21]:
a

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
c = a.copy()
c

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
d = np.array(([5,10,15],[20,25,30],[35,40,45]))
d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
d[1]

array([20, 25, 30])

In [25]:
d[1][1]

25

In [26]:
d[:2,1:]

array([[10, 15],
       [25, 30]])

In [27]:
x = np.zeros((10,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
y = x.shape[1]

In [29]:
for i in range(y):
  x[i]=i
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [30]:
x[[2,4,5,6]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [31]:
x[[6,8,4,9]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [33]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
a>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [36]:
b = a>4
b

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [38]:
a[b]

array([ 5,  6,  7,  8,  9, 10])

In [39]:
a[a>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
x = 2
a[a>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])